---
title: "final_project"
output: html_document
date: "2024-12-06"
---
```{r}
library(tidyverse)
library(haven)
```

```{r}
data <- read.csv("data.csv")

as.data.frame(seq_along(data), names(data))
data.final <- data[-c(1:2), 47:70]
colnames(data.final) <- paste0("Q", seq_along(data.final))
data.final$regular <- data[-c(1:2), 46]
data.final$exercise <- data[-c(1:2), 71]

data.final <- data.final %>% 
  mutate(across(Q1:Q24, ~case_when(
    . == "Never" ~ 1,
    . == "1-3 times a month" ~ 2,
    . == "Once a week" ~ 3,
    . == "Few times a week" ~ 4,
    . == "Once a day" ~ 5,
    . == "Few times a day" ~ 6
  )),
  regular = case_when(
    regular == "Yes, but only some of them" ~ 2,
    regular == "No" ~ 1,
    regular == "Yes, all of them" ~ 3
  ),
  exercise = case_when(
    exercise == "Less than 30 minutes" ~ 2,
    exercise == "1 hour to 2 hours" ~ 4,
    exercise == "30 minutes to 1 hour" ~ 3,
    exercise == "more than 2 hours" ~ 5,
    exercise == "Don't know / Prefer not to say" ~ 1
  )
)


write_dta(data.final, "data.dta")
```

